### ISSUE TITLE
Timestamp Crash

### ISSUE THREAD

**Issue by tristanmoney** [afourney/aprstastic#26]
Another amateur tried to use the gateway and it appears to crash aprstastic when their position is sent. The user is on iOS Meshtastic and has the timestamp enabled on their position, but maybe it comes in a different format from iOS or something. I use the Android Meshtastic and it works fine for me.

![Screenshot_20241102-091143](https://github.com/user-attachments/assets/e72caa18-5d82-4879-ac0f-0262b1a54ffb)

**Comment by tristanmoney** [comment]
I reset the registrations by "mv registrations.db old_registrations.db" and restarted aprstastic to get it going again, otherwise it would crash even after a restart (each time the position was reported from that user).

**Comment by afourney** [comment]
@tristanmoney , Thanks for the report. I think I've corrected the error here:

https://github.com/afourney/aprstastic/blob/0b1f399f6c263d043f83f5c7ad22d91466099fad/src/aprstastic/_gateway.py#L509C9-L519C81

APRS supports position reports that lack timestamps. I'm using that format here to push the missing timestamp up the stack. 

I'll read about it more. It's perhaps better for an iGate to add its own timestamp on receiving the message, so this behavior may change. 

In either case, it shouldn't crash.


PS: The reason you needed to clear the database is because the gateway was nolonger ignoring that other user's device (once registered). That was good debugging on your part but shouldn't be necessary anymore.

**Comment by afourney** [comment]
@tristanmoney at your earliest convenience, let me know if 0.0.1a21 resolved this problem for you? And I'll close the issue.

**Comment by tristanmoney** [comment]
Yes I believe this is fixed, the user who was getting the error (VA7LM) is properly registered now and appearing on aprs.fi. Thanks for the quick solution.
